
name: Reusable conda package builder

on:
  workflow_call:
    inputs:
      secret_name:
        description: "Name of secret to look for"
        required: true
        type: string
    outputs:
      available:
        value: ${{ jobs.check-secret.outputs.available }}

jobs:
    check-secret:
      runs-on: ubuntu-latest
      outputs:
        available: ${{ steps.secret-exists.outputs.available }}
      steps:
        - name: Check for ${{ inputs.secret_name }} availability
          id: secret-exists
          run: |
            if [ "${{ secrets[inputs.secret_name] }}" != '' ]; then
              echo "::set-output name=available::true"
            else
              echo "::set-output name=available::false"
            fi