on:
  workflow_call:
    inputs:
      deploy_type:
        description: "What type of doc deployment to undertake, option of: [test, update_latest, update_stable]"
        required: true
        type: string
      notebook_kernel:
        description: "If jupyter notebooks are included in the docs, specify the kernel name they expect, e.g. the package name"
        required: false
        type: string

defaults:
  run:
    shell: bash -l {0}

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # used to build docs into the gh-pages branch without losing branch history. See https://github.com/jimporter/mike/issues/49

    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: latest
        environment-name: ${{ github.event.repository.name }}-docs
        environment-file: requirements/base.txt
        create-args: >-
            -c city-modelling-lab
            -f requirements/dev.txt
            python=3.11
        post-cleanup: all
        cache-environment: true

    - name: install package to access the api-gen plugin
      run: |
        pip install --no-dependencies -e .

    - name: install jupyter kernel
      if: inputs.notebook_kernel != ''
      run: python -m ipykernel install --user --name ${{ inputs.notebook_kernel }}

    - name: Setup doc deploy
      run: |
        git config --global user.name Docs deploy
        git config --global user.email docs@dummy.bot.com

    - name: Test that docs build
      if: inputs.deploy_type == 'test'
      run: mike deploy develop

    - name: deploy docs to gh-pages branch
      if: inputs.deploy_type == 'update_latest'
      run: mike deploy --push develop

    - name: deploy docs to gh-pages branch
      if: inputs.deploy_type == 'update_stable'
      run: |
        mike deploy --push ${{ github.ref_name }}
        mike deploy --push --update-aliases ${{ github.ref_name }} stable
        mike set-default --push stable