name: Reusable template checker
on:
  workflow_call:

jobs:
  cruft-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: ${{ github.event.repository.name }}-cruft
          create-args: cruft python=3.11
          post-cleanup: all
          cache-environment: true

      - name: Check project against template
        id: check
        run: cruft check