name: Reusable template checker
on:
  workflow_call:

defaults:
  run:
    shell: bash -l {0}

jobs:
  copier-update:
    runs-on: ubuntu-latest
    env:
      UPDATE: "false"
      CONFLICTS: ""
    steps:
        - uses: actions/checkout@v4

        - uses: mamba-org/setup-micromamba@v2
          with:
            micromamba-version: '1.5.10-0'
            environment-name: ${{ github.event.repository.name }}-copier
            create-args: copier python=3.12
            post-cleanup: all
            cache-environment: true

        - name: Get current Copier commit to compare against
          run: |
            COMMIT=$(grep "_commit:" .copier-answers.yml | cut -f2 -d' ')
            SRC=$(grep "_src_path:" .copier-answers.yml | cut -f2 -d' ' | cut -f1 -f2 -d'.')
            echo "COMPARE=${SRC}/compare/${SRC}" >> $GITHUB_ENV

        - name: Add dummy GitHub credentials
          run: |
            git config --global user.name Copier update
            git config --global user.email check@dummy.bot.com

        - run: copier update -A -f

        - id: requires-update
          run: test -z "$(git status --porcelain)" || echo "UPDATE=true" >> $GITHUB_ENV

        - if: env.UPDATE == 'true'
          name: Find merge conflicts
          run: |
            {
              CONFLICTS=$(git diff --name-only --diff-filter=U --relative)
              echo 'CONFLICTS<<EOF'
              echo EOF
            } >> "$GITHUB_ENV"

        - if: env.UPDATE == 'true'
          name: Get commit compare URL
          run: |
            COMMIT=$(grep "_commit:" .copier-answers.yml | cut -f2 -d' ')
            echo "COMPARE=${{ env.COMPARE }}...${COMMIT}" >> $GITHUB_ENV

        - name: Comment on PR with request to update against template.
          if: env.UPDATE == 'true'
          uses: thollander/actions-comment-pull-request@v3
          with:
            message: |
              >[!CAUTION]
              >🤖 <beep boop> 🤖
              >This is the template updater bot.
              >Your project is out of date relative to the upstream template.
              >
              >Please run `copier update --skip-answered` and create a new PR with those changes.
              >
              >You can compare the template changes here: <${{ env.COMPARE }}>

              <details><summary>Click to view possible conflicts</summary>

              ${{ env.CONFLICTS }}

              </details>

            pr-number: ${{ github.event.number }}
            comment-tag: execution
