name: Reusable workflow validator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v2
        with:
          tool_versions: action-validator 0.5.3

      - name: Lint Actions
        run: |
          find workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
            | xargs -I {} action-validator --verbose {}